deploy_app:
  stage: deploy
  image: tagip/rancher-cli
  variables:
    GIT_SSL_NO_VERIFY: "true"
    CURL_CA_BUNDLE: "/var/lib/rancher/etc/ssl/ca.crt"
  script:
    - rancher --debug up -d --stack "sierra-reports"
    - rancher --debug up -d --force-upgrade --pull --stack "sierra-reports" --confirm-upgrade app